GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/5e68a7d67d1b9456234108aa

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
  "name": "Amazing Person",
  "subscribedToChannel": "Web Dev Simplified"
}

###

DELETE http://localhost:3000/subscribers/5e68aa11339cd456e2252aac

###

PATCH http://localhost:3000/subscribers/5e68a7d67d1b9456234108aa
Content-Type: application/json

{
  "name": "New name"
}